# Generated by Django 4.2.13 on 2024-07-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                ("role", models.CharField(max_length=100, verbose_name="Role")),
                (
                    "image",
                    models.ImageField(upload_to="team_images/", verbose_name="Image"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="titleNavbar",
        ),
    ]
