# Generated by Django 4.2.13 on 2024-07-09 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_galleryphoto_alter_teammember_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('start_time', models.DateTimeField()),
                ('youtube_link', models.URLField(unique=True, validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
