# Generated by Django 4.2.13 on 2024-07-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_carouselitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselitem',
            options={'verbose_name': 'images_carrousels', 'verbose_name_plural': 'images_carrousels'},
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='description',
            field=models.TextField(max_length=139, verbose_name='Description'),
        ),
    ]
