# Generated by Django 4.2.13 on 2024-07-09 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_livestream'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livestream',
            options={'verbose_name': 'Diffusion direct', 'verbose_name_plural': 'Diffusion direct'},
        ),
        migrations.AddField(
            model_name='livestream',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
