# Generated by Django 4.2.13 on 2024-07-17 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_carouselitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
