# Generated by Django 4.2.13 on 2024-07-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_carouselitem_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='img_src',
            field=models.ImageField(upload_to='carrousel/'),
        ),
    ]
