# Generated by Django 4.2.14 on 2024-07-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_carouselitem_img_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'église")),
                ('street_number', models.CharField(max_length=10, verbose_name='Numéro de rue')),
                ('street_name', models.CharField(max_length=255, verbose_name='Nom de la rue')),
                ('city', models.CharField(max_length=255, verbose_name='Ville')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Code postal')),
                ('country', models.CharField(max_length=255, verbose_name='Pays')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('mobile_phone', models.CharField(max_length=20, verbose_name='Téléphone portable')),
                ('rib_number', models.CharField(max_length=34, verbose_name='Numéro RIB')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('google_maps_url', models.URLField(blank=True, verbose_name='Google Maps URL')),
            ],
            options={
                'verbose_name': "Information de l'église",
                'verbose_name_plural': "Informations de l'église",
            },
        ),
    ]
