# Generated by Django 4.2.14 on 2025-02-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_livestream'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestYouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_embed_url', models.URLField(help_text="Collez ici l'URL du format iframe YouTube (ex: https://www.youtube.com/embed/VIDEO_ID).", verbose_name='URL intégrée de la dernière vidéo')),
            ],
        ),
    ]
