# Generated by Django 4.2.14 on 2025-02-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_latestyoutubevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="Téléchargez une image contenant les horaires de l'église.", upload_to='church_schedules/', verbose_name='Image des horaires')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
