# Generated by Django 4.2.14 on 2025-05-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_churchschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselitem',
            options={'verbose_name': 'Diaporama d’accueil', 'verbose_name_plural': 'Diaporama d’accueil'},
        ),
        migrations.AlterModelOptions(
            name='churchschedule',
            options={'verbose_name': 'Image des horaires de l’Église', 'verbose_name_plural': 'Images des horaires de l’Église'},
        ),
        migrations.AlterModelOptions(
            name='galleryphoto',
            options={'verbose_name': 'Photothèque de l’Église', 'verbose_name_plural': 'Photothèques de l’Église'},
        ),
        migrations.AlterModelOptions(
            name='latestyoutubevideo',
            options={'verbose_name': 'Dernière vidéo YouTube', 'verbose_name_plural': 'Dernières vidéos YouTube'},
        ),
        migrations.AlterModelOptions(
            name='livestream',
            options={'verbose_name': 'Diffusion en direct', 'verbose_name_plural': 'Diffusions en direct'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Équipe pastorale', 'verbose_name_plural': 'Équipes pastorales'},
        ),
        migrations.AlterField(
            model_name='churchinfo',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Google Maps URL'),
        ),
    ]
