# Generated by Django 4.2.14 on 2025-05-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_carouselitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSiteImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jesus_at_the_door', models.ImageField(upload_to='global_images/', verbose_name='Image - Jésus à la porte')),
                ('about', models.ImageField(upload_to='global_images/', verbose_name='Image - À propos')),
                ('video_explore', models.ImageField(upload_to='global_images/', verbose_name="Image - Vidéo 'Explorez notre Église'")),
                ('services_and_missions_kids_teaching', models.ImageField(upload_to='global_images/', verbose_name='Image - Enseignement des enfants et des jeunes')),
                ('services_and_missions_baptism', models.ImageField(upload_to='global_images/', verbose_name='Image - Baptême par immersion')),
                ('services_and_missions_evangelisation', models.ImageField(upload_to='global_images/', verbose_name='Image - Évangélisation')),
                ('services_and_missions_edification', models.ImageField(upload_to='global_images/', verbose_name='Image - Édification')),
            ],
            options={
                'verbose_name': 'Image globale du site',
                'verbose_name_plural': 'Images globales du site',
            },
        ),
    ]
