# Generated by Django 4.2.14 on 2025-05-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_globalsiteimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name="Logo de l'Église"),
        ),
    ]
