# Generated by Django 4.2.14 on 2025-05-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_churchinfo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchinfo',
            name='youtube_playlist',
            field=models.URLField(blank=True, verbose_name='Playlist YouTube'),
        ),
    ]
