# Generated by Django 4.2.14 on 2025-05-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_churchinfo_youtube_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestTestimonyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_embed_url', models.URLField(help_text="Collez ici l'URL du format iframe YouTube (ex: https://www.youtube.com/embed/VIDEO_ID).", verbose_name='URL intégrée de la dernière vidéo de témoignages')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dernière vidéo de témoignage',
                'verbose_name_plural': 'Dernières vidéos de témoignage',
            },
        ),
    ]
