# Generated by Django 4.2.13 on 2024-06-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('author_name', models.CharField(max_length=100, verbose_name="Author's Name")),
                ('publication_date', models.DateField(verbose_name='Publication Date')),
                ('text', models.TextField(verbose_name='Testimonial Text')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
