# Generated by Django 4.2.13 on 2024-06-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimony', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Témoignage', 'verbose_name_plural': 'Témoignages'},
        ),
    ]
