# Generated by Django 4.2.13 on 2024-07-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimony', '0002_alter_testimonial_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
