# Generated by Django 4.2.13 on 2024-07-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimony', '0004_testimonial_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
