# Generated by Django 4.2.14 on 2024-07-28 14:40

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testimony', '0006_alter_testimonial_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Testimonial Text'),
        ),
    ]
