# Generated by Django 4.2.13 on 2024-07-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Agenda', 'verbose_name_plural': 'Agenda'},
        ),
    ]
